### ISSUE TITLE
KeyError when defining top_x_feats less than feature count in dataset in feature_dict and caling plot_global_feat

### ISSUE THREAD

**Issue by jagandecapri** [feedzai/timeshap#15]
Hi,

Referring to the code block below for `Global feature-level` adapted from [AReM.ipynb](https://github.com/feedzai/timeshap/blob/main/notebooks/AReM/AReM.ipynb)

```
feature_dict = {'path': 'outputs/feature_all.csv', 'rs': 42, 'nsamples': 32000, 'feature_names': model_features, 'plot_features': plot_feats, 'top_x_feat': 3}
feat_data = feat_explain_all(f_hs, pos_dataset, sequence_id_feat, average_event, feature_dict, prun_indexes, model_features, time_feat)
feat_global_plot = plot_global_feat(feat_data, **feature_dict)
feat_global_plot
```

When I define `top_x_feat` as less than the number of features in the dataset, i.e: 3, in the `feature_dict`, there is an error `KeyError: '(...)'` when calling `plot_global_feat`.

**Comment by JoaoPBSousa** [comment]
Hi @jagandecapri,

Thank you for noting this issue, as this was indeed a problem. I pushed the fix to the repo already.

**Comment by jagandecapri** [comment]
Hi @JoaoPBSousa ,

Thank you for the fix.
