### ISSUE TITLE
Adaptation of TimeShap for multi-label classification and event classification.

### ISSUE THREAD

**Issue by marcosfmmota** [feedzai/timeshap#16]
Hello, thanks for the great paper and code. 

I'm exploring using timeshap for custom model and task. I reproduced the TensorFlow tutorial and all worked fine, but the AReM dataset was adapted from a multi-label to a binary classification so I'd like to know if there is the possibility to use timeshap for the original multi label setting. Also, if it is possible to use timeshap in the setting of classification of events, for a example given a sequence of length **l** classify each event between **n** labels. My question arrive from the limitation described in the README where the entry point should be a 3-D array `(#sequences; #sequence length; #features)` and output `(#sequence; 1)`.

**Comment by JoaoPBSousa** [comment]
Closed this issue due to inactivity. If you have any further questions feel free to re-open the issue or create a new one.
