### ISSUE TITLE
Upload Package to PyPI

### ISSUE THREAD

**Issue by JoaoPBSousa** [feedzai/timeshap#17]
Upload TimeSHAP package into PyPI.

**Comment by MikkelMathiasen23** [comment]
When do you expect to upload the package to PyPI? We would really like to try it out.

**Comment by JoaoPBSousa** [comment]
Hello @MikkelMathiasen23,

TimeSHAP is now available on PyPI. You can install it using `pip install timeshap`.
Link: https://pypi.org/project/timeshap/

If you have any further questions, don't hesitate to contact us.
