### ISSUE TITLE
How to speed up TIMESHAP computation

### ISSUE THREAD

**Issue by Changshu135** [feedzai/timeshap#21]
Hi all!

The package itself is really interesting and intuitive to use.
But I want to speed up TIMESHAP computation, Can I use gpu to calculate shapley values?
I used a device parameter in TorchModelWrapper, but efficiency of GPU is too low to accelerate TIMESHAP computation.
Any suggestion would be appreciated.

**Comment by JoaoPBSousa** [comment]
Hello @Changshu135,

Thanks for the interest and for trying out our package.
Currently the only way to speed up explanations is to reduce the time it takes for the model being explained to score all perturbations. This can be done through 3 ways: 
 1. Speed up the model (use GPU, increase batch size of the wrapper if you have GPU memory space for it); 
 2. Reduce the number of perturbations (nsamples);
 3. Reduce sequence length (increase pruning tolerance). 

If this does not help, feel free to provide more details so I can try to help you.

**Comment by JoaoPBSousa** [comment]
Closed this issue due to inactivity. If you have any further questions feel free to re-open the issue or create a new one.
