### ISSUE TITLE
CNN model

### ISSUE THREAD

**Issue by firmai** [feedzai/timeshap#22]
I currently have a CNN model, and previously had to do some strange hacking to get time series importance values. Your package now shines a better light on this issue. For multivariate forecasts CNNs still fair well, sometimes better than RNNs, from what I can see there is no reason why using CNNs won't working using your software. Let me know if I have that wrong.

**Comment by JoaoPBSousa** [comment]
Hello @firmai,

From what I understand of your issue, you are correct. TimeSHAP can explain any black-box model that receives a 3-D array (nsamples, timestamp, features) and outputs a score for that sequence or each element of that sequence. 
TimeSHAP does not require any type of architecture as the explained model as it uses data perturbations to obtain the explanations. 

Feel free to test TimeSHAP on your CNN models and open any issue regarding any troubles, bugs or doubts.

**Comment by JoaoPBSousa** [comment]
Closed this issue due to inactivity. If you have any further questions feel free to re-open the issue or create a new one.
