### ISSUE TITLE
TimeSHAP for text?

### ISSUE THREAD

**Issue by itsmemala** [feedzai/timeshap#24]
I'm working with a 1-layer GRU for text classification that takes BERT embeddings at the input. Each input sequence is of the shape (sequence length, bert-embedding-dimension). I'm looking for word level attribution scores for each sequence's prediction. Currently with the captum integrated gradients and occlusion explainers, I get attribution scores that are almost always the last few words of each sequence. This seems like it's stemming from the directional processing of GRU - any thoughts? 

Do you think TimeSHAP would be applicable for my use case? I suppose I could consider each word as an event and each embedding dimension as a feature, then I could use the event level local explanations from the library?
However, note that in my case, the events (i.e words) from the beginning of the sequence could be more important than those at the end of the sequence (i.e. most recent ones) - this violates the assumptions you use for your approximation (i.e pruning), so perhaps it's not applicable to text?

**Comment by JoaoPBSousa** [comment]
Hello @itsmemala,

Commenting on your first paragraph, I am sorry I cannot help you very much as I have not worked with BERT or the NLP domain. What I understand from the literature is that RNNs in general tend to be biased towards recent timestamps but should be capable of using information from more distant events without any problem.

About the application of TimeSHAP in your problem, I think this is possible but, as you described, only event explanations will be useful, as features and cell explanations will be regarding individual BERT embedding dimensions. 
Regarding the pruning algorithm, it assumes the recent events as the most recent ones, but it accommodates to the fact that that assumption might not stand. In that case, the pruning will simply not take place, and computations will use the whole sequence. If the model considers the first words important, the pruning algorithm will simply not prune them.

I hope I was helpful, don't hesitate to contact us If you have any further questions.

**Comment by JoaoPBSousa** [comment]
Closed this issue due to inactivity. If you have any further questions feel free to re-open the issue or create a new one.
