### ISSUE TITLE
Plot Coalition Pruning is not working

### ISSUE THREAD

**Issue by Erhtric** [feedzai/timeshap#25]
Hi, 
I am doing a project as part of a Master Thesis: I was testing your introductory notebook with the `Tensorflow` implementation, but this is not working because of an error raised by one of yours plot functions. The funny thing is that your other notebook, i.e., the one with the torch model, is working fine. I managed to find the issue and it was raised by an inner method called `solve_negatives_method` in  `src/timeshap/plot/pruning.py` which would raise an `InvalidKeyError` caused by this specific row:
```python
    df.at[corresponding_row.index, 'Shapley Value'] = corresponding_row['Shapley Value'].values[0] + row['Shapley Value']
``` 
As far I understood, we are passing a list, usually made of only one value, to the `pandas.DataFrame.at` method which requires to pass an integer parameter and a column identifier. As such, one solution that works now could be:
```python
    df.at[corresponding_row.index[0], 'Shapley Value'] = corresponding_row['Shapley Value'].values[0] + row['Shapley Value']
``` 

I want to thank you very much for the work done, and I will be happy to discuss further result of my thesis with you. :)
Hoping for the best and looking forward to hear from you,
Eric

**Comment by JoaoPBSousa** [comment]
Hello @Erhtric,
Thanks for noticing this and providing a solution!

We have tested both our notebooks and the error does not occur on our side, could you please provide your pandas version?

Regardless, the solution you provided is indeed a more correct way than what we had previously, and therefore we will update the repo accordingly.

Thank you very much once again

**Comment by Erhtric** [comment]
Hello @JoaoPBSousa,

Sorry for the delay, I will immediately provide you with the pandas version as requested: I am currently on `pandas 1.5.1`.

Thank you for the patience, 
Have a nice day!
