### ISSUE TITLE
TimeSHAP with different sequence length?

### ISSUE THREAD

**Issue by danhoonlee** [feedzai/timeshap#28]
Hello!
Thank you very much for your great work.

While reading your paper and going through the sample code using AReM dataset and trying to implement TimeSHAP in my own dataset, I came across some questions.

Please let me know if my understanding is not correct.
It seems that the bank fraud detection dataset in your paper has different sequence lengths if I am not mistaken.
So, in your example, there would be 32000 samples (number of clients?) with various sequence lengths or time lengths (with different number of transactions, logins, and enrollments per each client or sample), but with same number of features?

So, with that thought, I was going to use TimeSHAP in my dataset which has a different sequence length or time length but with the same number of features being used in each sequence.
Like the dimension of my dataset would be:
- number of samples : 611
- number of sequences: varies (approximately from 5 to 30)
- number of features: 18

In bank fraud case
- number of samples : 32000
- number of sequences: varies?
- number of features: ?

Would my scenario be used in TimeSHAP or does it have to have same length across the time?

Thank you very much and hope you could give some answers!
And please let me know if any part of my understanding is wrong.
Thank you!

**Comment by JoaoPBSousa** [comment]
Hello @danhoonlee,

In our bank fraud use case, we have a high number of clients with sequences ranging in length from 1 to 2187 events (Transactions, Logins, Enrollments) with the number of features equal across events and sequences.

Regarding the number of samples, the 32000 number is chosen as a parameter for TimeSHAP and it represents the number of perturbations that TimeSHAP is performing to obtain the explanations. For each explained sequence (each client), TimeSHAP will perform at max 32000 perturbations to explain that specific sequence. This number is independent of the number of sequences you have on your dataset, it should be chosen as a hyperparameter. 

From the information you provided TimeSHAP can be applied directly your use case.

If you have any further questions don't hesitate to contact us.

**Comment by danhoonlee** [comment]
Thank you very much @JoaoPBSousa for your kind reply.
It really helped in clearing uncertainties that I had.

Just one quick question about the "1.1 Data-Loading" part of the AReM case.
So, I presume that if I would like to run timeSHAP, as in the case of AReM, all samples needs to have the same sequence length?
This is because I see that for 'dataset8.csv' in folder 'sitting', it is short by one sequence and you have indicated to add a padding for this case to be used.
So, I thought if I want to use TimeSHAP in my dataset with various lengths of sequences, I would have to do the padding for all so that they all have the same sequence length.

Also, just one more thing.
If I were to use padding logic and add padding to the shorter sequence cases, would there be the best padding strategy to it or would TimeSHAP understand any padding logic such as using 0's or null's?

Thank you very much for your kind help!

**Comment by JoaoPBSousa** [comment]
Hello @danhoonlee,

TimeSHAP explains one individual sequence at a time, so no padding is required in any step of the algorithm.
 
Regarding the mentioned padding on step "1.1 Data-Loading" on the AReM notebook, this would only be used for the training of the model, and the padding should be discarded after.

Currently TimeSHAP does not deal with any kind of padding logic because no padding is required to be used. Please let us know if you find cases where this would be desirable.

If you have any further questions don't hesitate to contact us.

**Comment by danhoonlee** [comment]
Ah, now I understand how it should work!

Thank you very much @JoaoPBSousa !
If I find any case that you have mentioned at the bottom regarding the padding, I will let you know!

Thank you very much!
