### ISSUE TITLE
how to generate output/event_all.csv file or run event_explain_all? 

### ISSUE THREAD

**Issue by bryancoh** [feedzai/timeshap#31]
Hi, 
I am trying to use event_explain_all function of TimeSHAP with event_dict = {'rs': [42], 'nsamples': [32000]} and I get the error: 
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

If I add a path to the event dictionary, I can run the function without getting any error but then I get an empty output since the path I added doesn't exist 
How do you generate the output/event_all.csv file? 
Are you familiar with this error? 
Thanks

**Comment by JoaoPBSousa** [comment]
Closed this issue due to inactivity. If this error persists or you have any further questions feel free to re-open the issue or create a new one.
