### ISSUE TITLE
Tensorflow notebook, Local Report on positive instance error

### ISSUE THREAD

**Issue by ajbut5** [feedzai/timeshap#34]
Hi, thanks so much for the extensive documentation of your work. 

When running the tensorflow notebook however, I get the following error for the shown cell of the notebook. The only modification to the notebook was retrieving the csv files from google drive where they are located. I saw this was similar to a closed issue, my pandas version is 1.4.4, it did however work when I installed pandas 1.3.2 so it does seem to be an issue with the pandas version as you suspected.

Thank you so much.

![1](https://user-images.githubusercontent.com/129470755/229339932-8ed522a8-f373-4a95-9fab-965111c0e608.PNG)
![2](https://user-images.githubusercontent.com/129470755/229339930-d52215cf-86db-4478-ba12-c804903ebde8.PNG)
![3](https://user-images.githubusercontent.com/129470755/229339931-16bc9fdb-c2ff-46a6-bb28-f648d7ccf9d4.PNG)

**Comment by JoaoPBSousa** [comment]
Hi @ajbut5 ,

Thank you very much for letting us know and confirming this is the cause.

On the next version of TimeSHAP we will try to fix this error in order for the package to work with all recent versions of pandas.
