### ISSUE TITLE
Unable to install timeshap package

### ISSUE THREAD

**Issue by vishants98** [feedzai/timeshap#6]
Hello @feedzaiadmin , @saleiro ,

I am unable to run command "pip install timeshap" on my ubuntu system. It throws me below error:

ERROR: Could not find a version that satisfies the requirement timeshap (from versions: none)
ERROR: No matching distribution found for timeshap

Seems to me a compatibility issue. I have tried with python versions - 3.6,3.8. 
Is there any specific version which supports it? Will be waiting for response.

Thanks

**Comment by AndreFCruz** [comment]
Hi

`timeshap` is not yet on the public PyPi package.

In order to install it you first have to clone this repository to some folder, and then run
```
pip install <path-to-cloned-repo>
```

**Comment by vishants98** [comment]
Hi @AndreFCruz ,

I am trying to interpret an already trained LSTM model for time series which gives prediction in the form of probability. 
I have a doubt about hidden state variable. Is it the dimension of the hidden layer or something else?
Also my model outputs only one value which is prediction, but the below code in the torch wrappers function outputs two values. Does this mean I will have to customize this code based on my use case? 

                if hidden_states is not None:
                    hidden_states_tensor = torch.from_numpy(hidden_states)
                    predictions, hs = self.model(data_tensor, hidden_states_tensor)
                else:
                    predictions, hs = self.model(data_tensor)

**Comment by JoaoPBSousa** [comment]
Hi there @vishants98,

Thank you for reaching out.
Could you please open a new issue with this question?

Thank you very much,
João Bento

**Comment by vishants98** [comment]
Sure @JoaoPBSousa
